/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package com.omarsmarinhos.restaurant;

import glasspanepopup.GlassPanePopup;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import paneles.CambiarPanel;
import settings.Configuracion;
import settings.Message;

/**
 *
 * @author MenDark
 */
public class Principal extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        GlassPanePopup.install(this);
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.btn_inicio.setSelected(true);
        
        new CambiarPanel(pnlPrincipal, new paneles.pnlInicio());
        
         this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btn_inicio = new rsbutton.RSButtonMetro();
        btn_trabajadores = new rsbutton.RSButtonMetro();
        btn_cocina = new rsbutton.RSButtonMetro();
        btn_resumen = new rsbutton.RSButtonMetro();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btn_calendario = new rsbutton.RSButtonMetro();
        btn_usuarios = new rsbutton.RSButtonMetro();
        btn_menus = new rsbutton.RSButtonMetro();
        btn_locales = new rsbutton.RSButtonMetro();
        btn_appcliente = new rsbutton.RSButtonMetro();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rSButtonMetro2 = new rsbutton.RSButtonMetro();
        rSButtonMetro11 = new rsbutton.RSButtonMetro();
        rSButtonMetro12 = new rsbutton.RSButtonMetro();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();
        pnl_titulo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textField1 = new textfield.TextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1350, 720));
        setPreferredSize(new java.awt.Dimension(1257, 720));

        pnlMenu.setBackground(new java.awt.Color(53, 64, 83));

        jLabel1.setIcon(new ImageIcon("src/main/java/img/profileuser.png"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Boris Mendoza");

        jButton1.setIcon(new ImageIcon("src/main/java/img/fleha-abajo.png"));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(42, 53, 69));
        jSeparator1.setForeground(new java.awt.Color(42, 53, 69));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSeparator1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(121, 125, 129));
        jLabel3.setText("Admin");

        btn_inicio.setIcon(new ImageIcon("src/main/java/img/inicio.png"));
        btn_inicio.setText("INICIO");
        btn_inicio.setColorHover(new java.awt.Color(43, 53, 65));
        btn_inicio.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_inicio.setColorPressed(new java.awt.Color(33, 42, 52));
        btn_inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_inicioMousePressed(evt);
            }
        });
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_trabajadores.setBackground(new java.awt.Color(53, 64, 83));
        btn_trabajadores.setIcon(new ImageIcon("src/main/java/img/trabajadores.png"));
        btn_trabajadores.setText("TRABAJADORES");
        btn_trabajadores.setColorHover(new java.awt.Color(43, 53, 65));
        btn_trabajadores.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_trabajadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_trabajadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_trabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_trabajadoresMousePressed(evt);
            }
        });
        btn_trabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trabajadoresActionPerformed(evt);
            }
        });

        btn_cocina.setBackground(new java.awt.Color(53, 64, 83));
        btn_cocina.setIcon(new ImageIcon("src/main/java/img/cocina.png"));
        btn_cocina.setText("COCINA");
        btn_cocina.setColorHover(new java.awt.Color(43, 53, 65));
        btn_cocina.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_cocina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cocina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cocina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cocinaMousePressed(evt);
            }
        });
        btn_cocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cocinaActionPerformed(evt);
            }
        });

        btn_resumen.setBackground(new java.awt.Color(53, 64, 83));
        btn_resumen.setIcon(new ImageIcon("src/main/java/img/resumen.png"));
        btn_resumen.setText("RESUMEN");
        btn_resumen.setColorHover(new java.awt.Color(43, 53, 65));
        btn_resumen.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_resumen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_resumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_resumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_resumenMousePressed(evt);
            }
        });
        btn_resumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resumenActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(42, 53, 69));
        jSeparator2.setForeground(new java.awt.Color(42, 53, 69));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSeparator2.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(121, 125, 129));
        jLabel4.setText("Main");

        btn_calendario.setBackground(new java.awt.Color(53, 64, 83));
        btn_calendario.setIcon(new ImageIcon("src/main/java/img/calendario-1.png"));
        btn_calendario.setText("CALENDARIO");
        btn_calendario.setColorHover(new java.awt.Color(43, 53, 65));
        btn_calendario.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_calendario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_calendario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_calendarioMousePressed(evt);
            }
        });
        btn_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendarioActionPerformed(evt);
            }
        });

        btn_usuarios.setBackground(new java.awt.Color(53, 64, 83));
        btn_usuarios.setIcon(new ImageIcon("src/main/java/img/usuarios.png"));
        btn_usuarios.setText("USUARIOS");
        btn_usuarios.setColorHover(new java.awt.Color(43, 53, 65));
        btn_usuarios.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_usuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_usuariosMousePressed(evt);
            }
        });
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });

        btn_menus.setBackground(new java.awt.Color(53, 64, 83));
        btn_menus.setIcon(new ImageIcon("src/main/java/img/menus.png"));
        btn_menus.setText("MENUS");
        btn_menus.setColorHover(new java.awt.Color(43, 53, 65));
        btn_menus.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_menus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_menus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menusMousePressed(evt);
            }
        });
        btn_menus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menusActionPerformed(evt);
            }
        });

        btn_locales.setBackground(new java.awt.Color(53, 64, 83));
        btn_locales.setIcon(new ImageIcon("src/main/java/img/locales.png"));
        btn_locales.setText("LOCALES");
        btn_locales.setColorHover(new java.awt.Color(43, 53, 65));
        btn_locales.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_locales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_locales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_locales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_localesMousePressed(evt);
            }
        });
        btn_locales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_localesActionPerformed(evt);
            }
        });

        btn_appcliente.setBackground(new java.awt.Color(53, 64, 83));
        btn_appcliente.setIcon(new ImageIcon("src/main/java/img/app.png"));
        btn_appcliente.setText("APP CLIENTE");
        btn_appcliente.setColorHover(new java.awt.Color(43, 53, 65));
        btn_appcliente.setColorNormal(new java.awt.Color(53, 64, 83));
        btn_appcliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_appcliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_appcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_appclienteMousePressed(evt);
            }
        });
        btn_appcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_appclienteActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(42, 53, 69));
        jSeparator3.setForeground(new java.awt.Color(42, 53, 69));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSeparator3.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(121, 125, 129));
        jLabel12.setText("Settings");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mi Cuenta");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Configuraciones");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cerrar Sesión");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(jButton1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_trabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cocina, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resumen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_locales, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_appcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)))
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)))))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_trabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_cocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_resumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_locales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_appcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        rSButtonMetro2.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(162, 172, 191)));
        rSButtonMetro2.setIcon(new ImageIcon("src/main/java/img/add_menu.png"));
        rSButtonMetro2.setColorHover(new java.awt.Color(21, 165, 251));
        rSButtonMetro2.setColorNormal(new java.awt.Color(255, 255, 255));
        rSButtonMetro2.setColorPressed(new java.awt.Color(21, 165, 251));
        rSButtonMetro2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonMetro2.setRolloverIcon(new ImageIcon("src/main/java/img/add_menu_hover.png"));

        rSButtonMetro11.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(162, 172, 191)));
        rSButtonMetro11.setIcon(new ImageIcon("src/main/java/img/add_user_hover.png"));
        rSButtonMetro11.setColorHover(new java.awt.Color(21, 165, 251));
        rSButtonMetro11.setColorNormal(new java.awt.Color(255, 255, 255));
        rSButtonMetro11.setColorPressed(new java.awt.Color(21, 165, 251));
        rSButtonMetro11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonMetro11.setRolloverIcon(new ImageIcon("src/main/java/img/add_user.png"));

        rSButtonMetro12.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro12.setIcon(new ImageIcon("src/main/java/img/s_menu.png"));
        rSButtonMetro12.setColorHover(new java.awt.Color(21, 165, 251));
        rSButtonMetro12.setColorNormal(new java.awt.Color(255, 255, 255));
        rSButtonMetro12.setColorPressed(new java.awt.Color(21, 165, 251));
        rSButtonMetro12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rSButtonMetro12.setRolloverIcon(new ImageIcon("src/main/java/img/s_menu_hover.png"));

        jLabel9.setIcon(new ImageIcon("src/main/java/img/edit_lapiz.png"));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setIcon(new ImageIcon("src/main/java/img/status_abierto.png"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(498, 498, 498))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(rSButtonMetro11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSButtonMetro12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSButtonMetro12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetro11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        btn_menu.setIcon(new ImageIcon("src/main/java/img/btn_menu.png"));
        btn_menu.setBorderPainted(false);
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        pnl_titulo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new ImageIcon("src/main/java/img/restaurant_icon.png"));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 108, 119));
        jLabel5.setText("Pnale de Control de tu Restaurante");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(177, 186, 194));
        jLabel8.setText("Fogon Rustico");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 146, 222));
        jLabel7.setText("Personalizar nombre");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tituloLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addComponent(jLabel5))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tituloLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textField1.setLabelText("Buscar por categoría, palabra clave");
        textField1.setLineColor(new java.awt.Color(255, 131, 6));

        jLabel11.setIcon(new ImageIcon("src/main/java/img/lupa-icon.png"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(68, 68, 68)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
       new CambiarPanel(pnlPrincipal, new paneles.pnlInicio());
        if(this.btn_inicio.isSelected()){
            this.btn_inicio.setColorNormal(new Color(33,42,52));
            this.btn_inicio.setColorHover(new Color(33,42,52));
            this.btn_inicio.setColorPressed(new Color(33,42,52));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(43,53,65));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_trabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trabajadoresActionPerformed
        new CambiarPanel(pnlPrincipal, new paneles.pnlTrabajadores());
        if(this.btn_trabajadores.isSelected()){
            this.btn_trabajadores.setColorNormal(new Color(33,42,52));
            this.btn_trabajadores.setColorHover(new Color(33,42,52));
            this.btn_trabajadores.setColorPressed(new Color(33,42,52));
            
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(33,42,52));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(43,53,65));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_trabajadoresActionPerformed

    private void btn_inicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMousePressed
        this.btn_inicio.setSelected(true);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_inicioMousePressed

    private void btn_trabajadoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trabajadoresMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(true);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_trabajadoresMousePressed

    private void btn_cocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cocinaActionPerformed
        new CambiarPanel(pnlPrincipal, new paneles.pnlCocina());
        if(this.btn_cocina.isSelected()){
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(33,42,52));
            this.btn_cocina.setColorHover(new Color(33,42,52));
            this.btn_cocina.setColorPressed(new Color(33,42,52));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(43,53,65));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_cocinaActionPerformed

    private void btn_cocinaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cocinaMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(true);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_cocinaMousePressed

    private void btn_resumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resumenActionPerformed
       new CambiarPanel(pnlPrincipal, new paneles.pnlResumen());
        if(this.btn_resumen.isSelected()){
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(33,42,52));
            this.btn_resumen.setColorHover(new Color(33,42,52));
            this.btn_resumen.setColorPressed(new Color(33,42,52));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_resumenActionPerformed

    private void btn_resumenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resumenMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(true);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_resumenMousePressed

    private void btn_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calendarioActionPerformed
        new CambiarPanel(pnlPrincipal, new paneles.pnlCalendario());
        if(this.btn_calendario.isSelected()){
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(33,42,52));
            
            this.btn_calendario.setColorNormal(new Color(33,42,52));
            this.btn_calendario.setColorHover(new Color(33,42,52));
            this.btn_calendario.setColorPressed(new Color(33,42,52));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_calendarioActionPerformed

    private void btn_calendarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calendarioMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(true);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_calendarioMousePressed

    private void btn_menusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menusActionPerformed
        new CambiarPanel(pnlPrincipal, new paneles.pnlMenus());
        if(this.btn_menus.isSelected()){
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(33,42,52));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(33,42,52));
            this.btn_menus.setColorHover(new Color(33,42,52));
            this.btn_menus.setColorPressed(new Color(33,42,52));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_menusActionPerformed

    private void btn_menusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menusMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(true);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_menusMousePressed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        new CambiarPanel(pnlPrincipal, new paneles.pnlUsuarios());
        if(this.btn_usuarios.isSelected()){
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(33,42,52));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(33,42,52));
            this.btn_usuarios.setColorHover(new Color(33,42,52));
            this.btn_usuarios.setColorPressed(new Color(33,42,52));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void btn_usuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(true);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_usuariosMousePressed

    private void btn_localesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_localesActionPerformed
        new CambiarPanel(pnlPrincipal, new paneles.pnlLocales());
        if(this.btn_locales.isSelected()){
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(33,42,52));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(33,42,52));
            this.btn_locales.setColorHover(new Color(33,42,52));
            this.btn_locales.setColorPressed(new Color(33,42,52));
            
            this.btn_appcliente.setColorNormal(new Color(53,64,83));
            this.btn_appcliente.setColorHover(new Color(43,53,65));
            this.btn_appcliente.setColorPressed(new Color(43,53,65));
        }else{
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_localesActionPerformed

    private void btn_localesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_localesMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(true);
        this.btn_appcliente.setSelected(false);
    }//GEN-LAST:event_btn_localesMousePressed

    private void btn_appclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_appclienteActionPerformed
        new CambiarPanel(pnlPrincipal, new paneles.pnlAppCliente());
        if(this.btn_appcliente.isSelected()){
            this.btn_inicio.setColorNormal(new Color(53,64,83));
            this.btn_inicio.setColorHover(new Color(43,53,65));
            this.btn_inicio.setColorPressed(new Color(43,53,65));
            
            this.btn_trabajadores.setColorNormal(new Color(53,64,83));
            this.btn_trabajadores.setColorHover(new Color(43,53,65));
            this.btn_trabajadores.setColorPressed(new Color(43,53,65));
            
            this.btn_cocina.setColorNormal(new Color(53,64,83));
            this.btn_cocina.setColorHover(new Color(43,53,65));
            this.btn_cocina.setColorPressed(new Color(43,53,65));
            
            this.btn_resumen.setColorNormal(new Color(53,64,83));
            this.btn_resumen.setColorHover(new Color(43,53,65));
            this.btn_resumen.setColorPressed(new Color(33,42,52));
            
            this.btn_calendario.setColorNormal(new Color(53,64,83));
            this.btn_calendario.setColorHover(new Color(43,53,65));
            this.btn_calendario.setColorPressed(new Color(43,53,65));
            
            this.btn_usuarios.setColorNormal(new Color(53,64,83));
            this.btn_usuarios.setColorHover(new Color(43,53,65));
            this.btn_usuarios.setColorPressed(new Color(43,53,65));
            
            this.btn_menus.setColorNormal(new Color(53,64,83));
            this.btn_menus.setColorHover(new Color(43,53,65));
            this.btn_menus.setColorPressed(new Color(43,53,65));
            
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
            
            this.btn_appcliente.setColorNormal(new Color(33,42,52));
            this.btn_appcliente.setColorHover(new Color(33,42,52));
            this.btn_appcliente.setColorPressed(new Color(33,42,52));
        }else{
            this.btn_locales.setColorNormal(new Color(53,64,83));
            this.btn_locales.setColorHover(new Color(43,53,65));
            this.btn_locales.setColorPressed(new Color(43,53,65));
        }
    }//GEN-LAST:event_btn_appclienteActionPerformed

    private void btn_appclienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_appclienteMousePressed
        this.btn_inicio.setSelected(false);
        this.btn_trabajadores.setSelected(false);
        this.btn_cocina.setSelected(false);
        this.btn_resumen.setSelected(false);
        this.btn_calendario.setSelected(false);
        this.btn_usuarios.setSelected(false);
        this.btn_menus.setSelected(false);
        this.btn_locales.setSelected(false);
        this.btn_appcliente.setSelected(true);
    }//GEN-LAST:event_btn_appclienteMousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
         x = evt.getX();
         y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        int posicion = pnlMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(260, 10, 2, 2, btn_menu);
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
            
            Animacion.Animacion.mover_izquierda(260, 10, 2, 2, pnlPrincipal);
            Animacion.Animacion.mover_izquierda(260, 10, 2, 2, pnl_titulo);
            
            //1387
            
            
            
        }else{
            Animacion.Animacion.mover_derecha(10, 261, 2, 2, btn_menu);
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
            
            Animacion.Animacion.mover_derecha(10, 261, 2, 2, pnlPrincipal);
            Animacion.Animacion.mover_derecha(10, 261, 2, 2, pnl_titulo);
            //pnlPrincipal.setSize(1387, 565);
            
        }
    }//GEN-LAST:event_btn_menuActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
         Message obj = new Message();
        obj.eventOK(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                GlassPanePopup.closePopupLast();
            }
        });
        GlassPanePopup.showPopup(obj);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Configuracion obj = new Configuracion();
        obj.eventOK(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                GlassPanePopup.closePopupLast();
            }
        });
        GlassPanePopup.showPopup(obj);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
         System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbutton.RSButtonMetro btn_appcliente;
    private rsbutton.RSButtonMetro btn_calendario;
    private rsbutton.RSButtonMetro btn_cocina;
    private rsbutton.RSButtonMetro btn_inicio;
    private rsbutton.RSButtonMetro btn_locales;
    private javax.swing.JButton btn_menu;
    private rsbutton.RSButtonMetro btn_menus;
    private rsbutton.RSButtonMetro btn_resumen;
    private rsbutton.RSButtonMetro btn_trabajadores;
    private rsbutton.RSButtonMetro btn_usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnl_titulo;
    private rsbutton.RSButtonMetro rSButtonMetro11;
    private rsbutton.RSButtonMetro rSButtonMetro12;
    private rsbutton.RSButtonMetro rSButtonMetro2;
    private textfield.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
